### ISSUE TITLE
error_logger_lager_h exiting on gen_statem timeouts

### ISSUE THREAD

**Issue by PiedPieper** [erlang-lager/lager#471] opened 2018-08-29 21:06 UTC
Hi,

Should error_logger_lager_h be exiting on timeout events?

> handle_event(state_timeout, _Msg, StateName, State) ->
>    {stop, timeout};

I am exiting "gracefully" from a gen_statem timeout, but error_logger_lager_h is crashing:

> 21:02:04.591 [error] <0.584.0> Undefined:Undefined(Undefined):  Lager event handler error_logger_lager_h exited with reason {'EXIT',{{badmatch,[test_module,{state_timeout,timeout_event},[{data,[{"State",{init_delete,{state,undefined,443}}}]}],exit,timeout,[handle_event_function,state_enter],[{gen_statem,parse_event_result,8,[{file,"gen_statem.erl"},{line,1267}]},{gen_statem,loop_event,6,[{file,"gen_statem.erl"},{line,1015}]},{proc_lib,init_p_do_apply,3,[{file,...},...]}]]},...}}
> 21:02:04.610 [debug] <0.584.0> lager_handler_watcher:Undefined(119):  Lager installed handler error_logger_lager_h into error_logger

**Comment by Vagabond** [comment] 2018-08-29 21:32
Looks like you have found an edge case in the statem message parsing.

A good way to get a better error (to help us fix it) is to re-install the error_logger_tty_h event handler and provoke the crash again:

```erlang
gen_event:add_handler(error_logger, error_logger_tty_h, []).
```

**Comment by PiedPieper** [comment] 2018-08-29 21:56
=ERROR REPORT==== 29-Aug-2018::21:51:55 ===
** State machine test_module terminating
** Last event = {state_timeout,timeout_event}
** When server state  = [{data,
                             [{"State",
                               {init_auth,
                                   {state, undefined,
                                       443}}}]}]
** Reason for termination = exit:timeout
** Callback mode = [handle_event_function,state_enter]
** Stacktrace =
**  [{gen_statem,parse_event_result,8,[{file,"gen_statem.erl"},{line,1267}]},
     {gen_statem,loop_event,6,[{file,"gen_statem.erl"},{line,1015}]},
     {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]

=CRASH REPORT==== 29-Aug-2018::21:51:55 ===
  crasher:
    initial call: test_module:init/1
    pid: <0.662.0>
    registered_name: test_module
    exception exit: timeout
      in function  gen_statem:parse_event_result/8 (gen_statem.erl, line 1267)
      in call from gen_statem:loop_event/6 (gen_statem.erl, line 1015)
    ancestors: [smdpp_proxy_sup,<0.649.0>]
    message_queue_len: 0
    messages: []
    links: [<0.650.0>]
    dictionary: [{rand_seed,{#{bits => 58,jump => #Fun<rand.8.15449617>,
                                next => #Fun<rand.5.15449617>,type => exrop,
                                uniform => #Fun<rand.6.15449617>,
                                uniform_n => #Fun<rand.7.15449617>,
                                weak_low_bits => 1},
                              [33862851821308965|132864393229953609]}}]
    trap_exit: true
    status: running
    heap_size: 4185
    stack_size: 27
    reductions: 16475
  neighbours:

=SUPERVISOR REPORT==== 29-Aug-2018::21:51:55 ===
     Supervisor: {local,test_module_sup}
     Context:    child_terminated
     Reason:     timeout
     Offender:   [{pid,<0.662.0>},
                  {id,test_module_8944500803162022175F},
                  {mfargs,{test_module,start,undefined}},
                  {restart_type,temporary},
                  {shutdown,1000},
                  {child_type,worker}]

=ERROR REPORT==== 29-Aug-2018::21:51:55 ===
** gen_event handler error_logger_lager_h crashed.
** Was installed in error_logger
** Last event was: {error,<0.648.0>,
                    {<0.662.0>,
                     "** State machine ~tp terminating~n** Last event = ~tp~n** When server state  = ~tp~n** Reason for termination = ~w:~tp~n** Callback mode = ~p~n** Stacktrace =~n**  ~tp~n",
                     [test_module,
                      {state_timeout,timeout_event},
                      [{data,
                        [{"State",
                          {init_auth,
                           {state,undefined,
                            443}}}]}],
                      exit,timeout,
                      [handle_event_function,state_enter],
                      [{gen_statem,parse_event_result,8,
                        [{file,"gen_statem.erl"},{line,1267}]},
                       {gen_statem,loop_event,6,
                        [{file,"gen_statem.erl"},{line,1015}]},
                       {proc_lib,init_p_do_apply,3,
                        [{file,"proc_lib.erl"},{line,247}]}]]}}
** When handler state == {state,lager_event,
                                {lager_shaper,50,1,{1535,579300,859439},0},
                                handle,false}
** Reason == {{badmatch,
                  [test_module,
                   {state_timeout,timeout_event},
                   [{data,
                        [{"State",
                          {init_auth,
                              {state,
                                  undefined, 
                                  443}}}]}],
                   exit,timeout,
                   [handle_event_function,state_enter],
                   [{gen_statem,parse_event_result,8,
                        [{file,"gen_statem.erl"},{line,1267}]},
                    {gen_statem,loop_event,6,
                        [{file,"gen_statem.erl"},{line,1015}]},
                    {proc_lib,init_p_do_apply,3,
                        [{file,"proc_lib.erl"},{line,247}]}]]},
              [{error_logger_lager_h,log_event,2,
                   [{file,
                        "/home/ec2-user/repos/test_module/_checkouts/lager/src/error_logger_lager_h.erl"},
                    {line,155}]},
               {gen_event,server_update,4,[{file,"gen_event.erl"},{line,573}]},
               {gen_event,server_notify,4,[{file,"gen_event.erl"},{line,555}]},
               {gen_event,server_notify,4,[{file,"gen_event.erl"},{line,557}]},
               {gen_event,handle_msg,6,[{file,"gen_event.erl"},{line,296}]},
               {proc_lib,init_p_do_apply,3,
                   [{file,"proc_lib.erl"},{line,247}]}]}

**Comment by Vagabond** [comment] 2018-08-29 22:03
And what version of lager is this? Have you tried with the latest release (3.6.4)?

**Comment by PiedPieper** [comment] 2018-08-30 00:09
@Vagabond 
[ec2-user@ip-172-31-16-9 lager]$ git rev-parse HEAD
82652f57c0976167edfa8bc3ecfcd03b915eede5

up-to-date with master

**Comment by Vagabond** [comment] 2018-08-30 00:30
It *looks* like your statem state is getting wrapped in a list, which is causing the failure:

```
[{data,[{"State",{init_auth,{state,undefined,443}}}]}]
```

I will extend our statem tests to see if I can reproduce this.

**Comment by PiedPieper** [comment] 2018-08-30 13:35
@Vagabond , Sorry about that, I was using an older version before you commented but I upgraded and had the same issue. Here are the results from the current master:

```

[error] [Client <0.633.0>] Unexpected Info when connected: {'EXIT',<0.660.0>,
                                                            {function_clause,
                                                             [{test_module,
                                                               operator_login,
                                                               [state_timeout,
                                                                timeout_event,
                                                                {state,
                                                                 <<"123">>,
                                                                 <<"develop">>,
                                                                 30000,
                                                                 undefined,
                                                                 undefined}],
                                                               [{file,
                                                                 "/home/ec2-user/repos/test_module/_build/default/lib/test_module/src/test_module.erl"},
                                                                {line,114}]},
                                                              {gen_statem,
                                                               call_state_function,
                                                               5,
                                                               [{file,
                                                                 "gen_statem.erl"},
                                                                {line,1240}]},
                                                              {gen_statem,
                                                               loop_event,6,
                                                               [{file,
                                                                 "gen_statem.erl"},
                                                                {line,1012}]},
                                                              {proc_lib,
                                                               init_p_do_apply,
                                                               3,
                                                               [{file,
                                                                 "proc_lib.erl"},
                                                                {line,
                                                                 247}]}]}}

=CRASH REPORT==== 30-Aug-2018::13:32:31 ===
  crasher:
    initial call: test_module:init/1
    pid: <0.660.0>
    registered_name: []
    exception error: no function clause matching 
                     test_module:operator_login(state_timeout,
                                                               timeout_event,
                                                               {state,
                                                                <<"123">>,
                                                                <<"develop">>,
                                                                30000,
                                                                undefined,
                                                                undefined}) (/home/ec2-user/repos/test_module/_build/default/lib/test_module/src/test_module.erl, line 114)
      in function  gen_statem:call_state_function/5 (gen_statem.erl, line 1240)
      in call from gen_statem:loop_event/6 (gen_statem.erl, line 1012)
    ancestors: [<0.633.0>,<0.632.0>,<0.631.0>,<0.629.0>,emqttc_sup,
                  <0.627.0>]
    message_queue_len: 0
    messages: []
    links: [<0.633.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 1885
  neighbours:
13:32:31.148 [error] <0.587.0> Undefined:Undefined(Undefined):  Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[test_module_123,{state_timeout,timeout_event},[{data,[{"State",{operator_login,{state,<<"123">>,<<"develop">>,30000,undefined,undefined}}}]}],error,function_clause,[state_functions,state_enter],[{test_module,operator_login,[state_timeout,timeout_event,{state,<<"123">>,<<"develop">>,30000,undefined,undefined}],[{file,"/home/ec2-user/repos/test_module/_build/default/lib/test_module/src/test_module.erl"},{line,114}]},{gen_statem,call_state_function,...},...]]},...}}
13:32:31.154 [debug] <0.587.0> lager_handler_watcher:Undefined(126):  Lager installed handler error_logger_lager_h into error_logger
```

**Comment by Vagabond** [comment] 2018-08-30 15:52
So, from my reading of the gen_statem man page, a timeout is not a valid action to return from init:

```
    Module:init(Args) -> Result(StateType)

              Types:
                 Args = term()
                  Result(StateType) = init_result(StateType)

    init_result(StateType) =
           {ok, State :: StateType, Data :: data()} |
           {ok,
            State :: StateType,
            Data :: data(),
            Actions :: [action()] | action()} |
           ignore |
           {stop, Reason :: term()}

    action() =
           postpone |
           {postpone, Postpone :: postpone()} |
           {next_event,
            EventType :: event_type(),
            EventContent :: term()} |
           enter_action()
```

This is probably a bug in gen_statem not checking the return type from init. That said, I have a patch to stop lager crashing when it encounters this issue. I'm not sure we should add a test case for it however as it's undefined behaviour.

**Comment by PiedPieper** [comment] 2018-08-30 16:31
@Vagabond We experience this issue whether or not we pass it through init:

Code:

```
init([]) ->
    process_flag(trap_exit, true),
    gen_statem:cast(self(), set_a_timeout),
    {ok, state_name, #state{}}.



state_name(cast, set_a_timeout, _Data) ->
    {keep_state_and_data, {state_timeout, 3000, timeout}};
state_name(state_timeout, _Msg, _Data) ->
    {stop, timeout}.

```

Result:

```
test:start_link().
{ok,<0.664.0>}
** exception error: timeout 
(SMDPP_PROXY@10.26.0.195)3> 
=CRASH REPORT==== 30-Aug-2018::16:28:21 ===
  crasher:
    initial call: test:init/1
    pid: <0.664.0>
    registered_name: test
    exception exit: timeout
      in function  gen_statem:parse_event_result/8 (gen_statem.erl, line 1267)
      in call from gen_statem:loop_event/6 (gen_statem.erl, line 1015)
    ancestors: [<0.662.0>]
    message_queue_len: 0
    messages: []
    links: [<0.662.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 402
  neighbours:
    neighbour:
      pid: <0.662.0>
      registered_name: []
      initial_call: {erlang,apply,2}
      current_function: {shell,eval_loop,3}
      ancestors: []
      message_queue_len: 0
      links: [<0.553.0>,<0.664.0>]
      trap_exit: false
      status: waiting
      heap_size: 233
      stack_size: 7
      reductions: 1071
      current_stacktrace: [{shell,eval_loop,3,[{file,"shell.erl"},{line,622}]}]
16:28:21.911 [error] <0.587.0> Undefined:Undefined(Undefined):  Lager event handler error_logger_lager_h exited with reason {'EXIT',{{case_clause,[test,{state_timeout,timeout},[{data,[{"State",{state_name,{state}}}]}],exit,timeout,state_functions,[{gen_statem,parse_event_result,8,[{file,"gen_statem.erl"},{line,1267}]},{gen_statem,loop_event,6,[{file,"gen_statem.erl"},{line,1015}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]]},[{error_logger_lager_h,log_event,2,[{file,"/home/ec2-user/repos/smdpp_proxy/_checkouts/lager/src/error_logger_lager_h.erl"},{line,206}]},{gen_event,server_update,4,[{file,...},...]},...]}}
16:28:21.916 [debug] <0.587.0> lager_handler_watcher:Undefined(126):  Lager installed handler error_logger_lager_h into error_logger
```

Now that I'm trying different things, I think the issue is with {stop, Reason}. If I return stop, there is no error:

```
state_name(state_timeout, _Msg, _Data) ->
    stop.

```

> test:start_link().
> {ok,<0.669.0>}
> (No lager crash)

**Comment by Vagabond** [comment] 2018-08-31 14:32
Have you tried the branch in the linked PR?

**Comment by PiedPieper** [comment] 2018-08-31 15:26
No longer a lager error, looks like an issue with the gen_statem module itself

```
state_name(cast, set_a_timeout, _Data) ->
     {keep_state_and_data, {state_timeout, 3000, timeout}};
state_name(state_timeout, _Msg, _Data) ->
     {stop, finished}.

```


```
=CRASH REPORT==== 31-Aug-2018::15:22:44 ===
  crasher:
    initial call: test:init/1
    pid: <0.834.0>
    registered_name: test
    exception exit: finished
      in function  gen_statem:parse_event_result/8 (gen_statem.erl, line 1267)
      in call from gen_statem:loop_event/6 (gen_statem.erl, line 1015)
    ancestors: [<0.831.0>]
    message_queue_len: 0
    messages: []
    links: [<0.831.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 402
  neighbours:
    neighbour:
      pid: <0.831.0>
      registered_name: []
      initial_call: {erlang,apply,2}
      current_function: {shell,eval_loop,3}
      ancestors: []
      message_queue_len: 0
      links: [<0.704.0>,<0.834.0>]
      trap_exit: false
      status: waiting
      heap_size: 233
      stack_size: 7
      reductions: 1071
      current_stacktrace: [{shell,eval_loop,3,[{file,"shell.erl"},{line,622}]}]
15:22:44.592 [error] <0.834.0> Undefined:Undefined(Undefined):  gen_statem test in state data terminated with reason: finished in gen_statem:parse_event_result/8 line 1267
15:22:44.592 [error] <0.834.0> Undefined:Undefined(Undefined):  CRASH REPORT Process test with 1 neighbours exited with reason: finished in gen_statem:parse_event_result/8 line 1267
```

**Comment by PiedPieper** [comment] 2018-08-31 15:36
Thanks for your help!

If I may ask one last question - In your experience, should erlang be throwing a crash report when exiting with {stop, Reason}?

**Comment by Vagabond** [comment] 2018-08-31 15:41
I believe any `abnormal` exit will trigger a message like this, `normal` and `shutdown` are the two normal exit reasons.

**Comment by PiedPieper** [comment] 2018-08-31 15:46
I see you are supposed to pass a reason with {stop, {shutdown, Reason}} if you want terminate to handle it.

Again, thanks for your help!

**Comment by Vagabond** [comment] 2018-09-03 17:58
Going to close this as I merged the PR to handle this weirdness to master.

**Closed by Vagabond** 2018-09-03 17:58 UTC
