### ISSUE TITLE
lager_error_logger_h dropped 0 messages in the last second that exceeded the limit of 100 messages/sec

### ISSUE THREAD

**Issue by oneiros-de** [erlang-lager/lager#438] opened 2018-01-29 08:59 UTC
With RabbitMQ 3.7.2 (which uses lager) and Erlang 20.1 on Debian 8, we get log lines like these:

```
2018-01-27 07:54:27.042 [warning] <0.32.0> lager_error_logger_h dropped 0 messages in the last second that exceeded the limit of 100 messages/sec
2018-01-27 07:55:32.066 [warning] <0.32.0> lager_error_logger_h dropped 2 messages in the last second that exceeded the limit of 100 messages/sec
2018-01-27 07:58:41.218 [warning] <0.32.0> lager_error_logger_h dropped 0 messages in the last second that exceeded the limit of 100 messages/sec
2018-01-27 07:59:17.220 [warning] <0.32.0> lager_error_logger_h dropped 0 messages in the last second that exceeded the limit of 100 messages/sec
```

These are consecutive, so clearly there were not >100 messages/sec in these last seconds (or I would expect to see at least some non-dropped log lines there).

But why is it _warning_ about **no** (0) dropped messages?

**Comment by Vagabond** [comment] 2018-02-01 16:44
I think this is a recent regression, I am preparing a fix right now.

**Comment by mrallen1** [comment] 2018-03-27 16:43
Closing this issue since the PR was merged. Please reopen if needed.

**Closed by mrallen1** 2018-03-27 16:43 UTC
