### ISSUE TITLE
Lager does not create a new log file immediately after the old log file is rotated

### ISSUE THREAD

**Issue by sergey-safarov** [erlang-lager/lager#402] opened 2017-04-12 06:06 UTC
After log rotation is not created new empty file.
This is required when used monitoring tools like zabbix to check file size.

Could you add ability to create new empty file after  log rotation.
P.S. As workaround may be used external log rotation.

```
[root@kazoo-app02 log]# ls -l
total 16920
-rw-r--r-- 1 kazoo daemon 2496086 Apr 12 07:02 console.log
-rw-r--r-- 1 kazoo daemon 8534767 Apr 11 23:59 console.log.1
-rw-r--r-- 1 kazoo daemon 5485187 Apr 10 23:59 console.log.3
-rw-r--r-- 1 kazoo daemon  675063 Apr 10 00:00 console.log.4
-rw-r--r-- 1 kazoo daemon       0 Apr 11 15:40 crash.log.1
-rw-r--r-- 1 kazoo daemon   69156 Apr  8 09:56 crash.log.4
-rw-r--r-- 1 kazoo daemon    2106 Apr 11 15:40 error.log.1
-rw-r--r-- 1 kazoo daemon   35375 Apr  8 09:56 error.log.4
```

**Comment by mrallen1** [comment] 2017-04-12 15:28
I'm not sure I understand what you're asking for in this ticket.  Do you mean you want lager to create a zero-length file immediately after it renames the previous log file?

**Comment by sergey-safarov** [comment] 2017-04-12 16:42
Correct required "to create a zero-length file immediately after it renames the previous log file"

**Comment by mrallen1** [comment] 2017-04-12 17:05
OK, thanks for the confirmation.

**Comment by Vagabond** [comment] 2017-04-12 17:29
Yeah, we should probably do this, it does cause weird gaps in the log file sequence that can make you worry you missed something.

**Comment by Vagabond** [comment] 2017-04-12 17:31
I think this was not entirely straightforward to implement, given how rotation works, but I may be wrong.

**Comment by sergey-safarov** [comment] 2017-04-12 18:57
@Vagabond is required to do by me?

**Comment by sergey-safarov** [comment] 2017-04-12 18:58
is required some thing to do by me?

**Comment by mrallen1** [comment] 2017-04-12 19:02
@sergey-safarov Only if you're interested in doing it. No obligation- raising the issue is a good start.

**Comment by sergey-safarov** [comment] 2017-04-12 19:06
@mrallen1 may be I like baby but
Is this ticket is "raises the issue"?

**Comment by mrallen1** [comment] 2017-04-12 19:09
@sergey-safarov You're not like a baby :) 

Thanks for pointing out this gap - it would be a useful feature to implement. (You are not under any obligation to do that though.)

**Comment by mrallen1** [comment] 2018-12-21 23:01
I think #474 solved this problem so I am going to close this ticket.

**Closed by mrallen1** 2018-12-21 23:01 UTC
Labels: Help Wanted
