### ISSUE TITLE
relative path in log_root has no effect [JIRA: RIAK-2722]

### ISSUE THREAD

**Issue by chatterbeak** [erlang-lager/lager#369] opened 2016-07-28 20:10 UTC
If I do this:

```
  {lager, [
    {log_root, "./log"},
    {handlers, [
      {lager_console_backend, info},
      {lager_file_backend, [{file, "error.log"}, {level, error}]},
      {lager_file_backend, [{file, "console.log"}, {level, info}]}
    ]}
   ]},
```

the log_root is ignored, and the log files go into the cwd. This will work

```

  {lager, [
    {handlers, [
      {lager_console_backend, info},
      {lager_file_backend, [{file, "log/error.log"}, {level, error}]},
      {lager_file_backend, [{file, "log/console.log"}, {level, info}]}
    ]}
   ]},
```

 {git,"https://github.com/basho/lager.git",{tag,"2.1.0"}}

**Comment by mrallen1** [comment] 2016-07-28 21:12
Better relative path handling was implemented in release `2.1.1` - recommend you switch to a more recent tag such as `3.2.1`or the most current 2.x tag `2.2.3`

Here's the code which expands paths in recent lager releases: https://github.com/basho/lager/blob/master/src/lager_util.erl#L481-L495

**Comment by chatterbeak** [comment] 2016-07-28 21:28
Thanks! I'll upgrade to 2.2.3.

**Comment by mrallen1** [comment] 2016-07-28 22:13
I admit I'm confused by that behavior. Just running some tests from the erlang REPL suggests it ought to work.

```
5> application:set_env(lager, log_root, "./log").                                    
ok
6> lager_util:expand_path("error.log").
"./log/error.log"
```

Now I wonder if the problem is inside `lager_file_backend.erl`

**Comment by chatterbeak** [comment] 2016-07-28 22:27
were you able to confirm? Let me know if you want me to run any tests! You
can DM me in #erlounge "thrillscience"

**Comment by mrallen1** [comment] 2016-07-29 05:17
I made a unit test and it *seems* like this might be a bug somewhere in OTP. Still investigating. 

https://github.com/basho/lager/compare/master...mrallen1:file_open?expand=1

**Comment by mrallen1** [comment] 2016-07-29 05:19
I originally thought this might a race condition due to the use of buffered writes in `file:open/2` but it happens on unbuffered writes too.  I'll have a look at the source code for io:write/2 tomorrow.

```
mallen-rMBP:lager mallen$ erl -pz deps/*/ebin .eunit ebin
Erlang/OTP 19 [erts-8.0.2] [source] [64-bit] [smp:8:8] [async-threads:10] [kernel-poll:false] [dtrace]

Eshell V8.0.2  (abort with ^G)
1> eunit:test(lager_file_open).
test/lager_file_open.erl:20:<0.62.0>: Removing files
test/lager_file_open.erl:23:<0.62.0>: Test run: 10

test/lager_file_open.erl:27:<0.62.0>: Path: "./test3/log4.log"

test/lager_file_open.erl:30:<0.62.0>: Using unbuffered writes
test/lager_file_open.erl:36:<0.62.0>: Inode: 55981996, Size: 0

test/lager_file_open.erl:46:<0.62.0>: Writing message 95
lager_file_open: file_open_test (module 'lager_file_open')...*failed*
in function io:request/2 (io.erl, line 556)
  called as request({file_descriptor,prim_file,{#Port<0.924>,33}},{write,<<"This is message 95\n">>})
in call from io:o_request/3 (io.erl, line 63)
in call from lager_file_open:write/2 (test/lager_file_open.erl, line 48)
in call from lager_file_open:file_open/1 (test/lager_file_open.erl, line 37)
**error:function_clause
  output:<<"">>

=======================================================
  Failed: 1.  Skipped: 0.  Passed: 0.
error
```

**Comment by chatterbeak** [comment] 2016-07-29 16:43
Wow! I didn't think this would be such a rabbit hole! :-)
Thanks for your attention. Maybe I should just move up to 3? I could use a
custom sink.

**Comment by mrallen1** [comment] 2016-07-29 20:22
I walked through the whole code chain today from `file:open` to `file:write` - the only thing I can think is that the period is being lost when the NIF converts the Erlang list to a latin1 string in C-land. I'm going to turn on DTrace tonight from my not-work laptop and watch it go through a minimal reproducer module.  Then I'll file a bug on https://bugs.erlang.org

**Comment by mrallen1** [comment] 2016-07-29 20:24
Also this problem happens on 3.x branch too - it's somewhere in the guts of OTP.  For now the best solution is the workaround you've already suggested, simply drop the `./` from the path.

**Comment by mrallen1** [comment] 2016-07-30 01:46
OK, it turns out I made a big mistake in my test code. With that mistake fixed up, I can't get this reproduced on OTP 19. What OTP release are you using?

**Comment by mrallen1** [comment] 2017-01-20 21:20
Any progress on this ticket? If not I will close it within 7 days. Thanks.

**Closed** 2017-02-17 00:22 UTC
