### ISSUE TITLE
lager_error_logger_h dropped X messages

### ISSUE THREAD

**Issue by Andy-Richards** [erlang-lager/lager#180] opened 2013-12-03 12:14 UTC
I randomly see warning messages reported from Lager 2.0.X as follows...

[warning] lager_error_logger_h dropped 633 messages in the last second that exceeded the limit of 50 messages/sec

As per this mailing list post http://erlang.org/pipermail/erlang-questions/2013-May/073773.html

Being random its difficult to produce a reproducible test case however I frequently see this warning when starting up an application where I assume there is considerable error_logger/SASL logging going when starting supervisors, gen_servers etc. 

Thanks,

Andy.

**Comment by grahamrhay** [comment] 2015-01-17 15:22
The problem is that the message is not displayed until an event arrives in a second later than the one in which the hwm was breached. So, if your app startup creates more than 50 messages (quite likely), but they all occur within one second; and the next event is not for a while (because nothing is happening), then you don't get the "dropped X messages" message until some time later. Which makes it look spurious, but it's technically correct, just not referring to the second you think it is.

Unfortunately I don't really have any suggestions to fix it, other than starting a timer, which I'm not sure is a good idea?

**Comment by rlipscombe** [comment] 2015-01-19 19:14
If the warning could refer to the second for which it dropped the messages, that'd be less confusing, potentially...

**Comment by grahamrhay** [comment] 2015-01-20 11:20
It also doesn't take into account whether the event would actually have been logged. If ?SHOULD_LOG returns false, then ?LOGFMT (or ?LOGMSG) is effectively a no-op. Wouldn't it make more sense to check that before counting the event towards the high water mark? The only thing I can see that that would affect is the crash log.

**Comment by sebmaynard** [comment] 2015-05-07 13:58
Just to add a bit of (potentially useless) extra info here:
Our app startup generates hundreds of lines of messages; this is quite normal as it's reporting that everything is firing up as expected; and we track the number of warnings that have been reported on each system

Could we mark something at startup as "don't worry about overloading for now" then turn it on again once the system has been up for a few seconds?

**Comment by jonmeredith** [comment] 2015-05-07 14:50
Riak also has this pattern - particularly when we launch a few nodes on the same machine for development testing.

**Comment by plainsane** [comment] 2015-09-21 22:19
the ghost messages could be caused by info reports in the form of progress.

we see this all the time in our applications but i traced it back to the spin up of new supervisors which we do a lot of.  if you look in the code they are logged with debug so if you enable debug logging i think you will see other messages logged between these drop messages.

its a shame that it does not filter these out if not logging debug messages, thus the velocity argument appears misleading.

**Comment by Vagabond** [comment] 2015-09-21 22:40
Yes, it is problematic. The main issue is trying to shed load quickly doesn't mesh well with trying to determine if we'd actually log the messages. If we can quickly determine if we would actually log the message, then yes, we could eliminate counting the 'ghost' messages towards  drops.

**Comment by Vagabond** [comment] 2017-05-28 03:10
#411 should address this, finally.

**Comment by mrallen1** [comment] 2017-10-19 21:59
Closing due to #411

**Closed by mrallen1** 2017-10-19 21:59 UTC
